default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gamesdb_development
  username: ubuntu
  password: peter

test:
  <<: *default
  database: gamesdb_test
  username: ubuntu
  password: peter
production:
  <<: *default
  database: gamesdb
  username: ~
  password: ~

